version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "15432:5432"
    volumes:
    - Downloads/api-restaurante/docs/docker_compose/PostgreSQL:/var/lib/postgresql/data # Defina aqui o diretório do seu docker-compose
    networks:
      - postgres-compose-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge